### ISSUE TITLE
为什么会出现这个错误？

### ISSUE THREAD

**Issue by njt123123** [WeiHeCnSH/CGCL-Pytorch-master#1]
Traceback (most recent call last):
  File "/tmp/CGCL-Pytorch-master-main/main.py", line 77, in <module>
    run_single_model(args)
  File "/tmp/CGCL-Pytorch-master-main/main.py", line 49, in run_single_model
    best_valid_score, best_valid_result = trainer.fit(
  File "/tmp/CGCL-Pytorch-master-main/trainer.py", line 61, in fit
    valid_score, valid_result = self._valid_epoch(valid_data, show_progress=show_progress)
  File "/root/miniconda3/lib/python3.10/site-packages/recbole/trainer/trainer.py", line 284, in _valid_epoch
    valid_result = self.evaluate(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/recbole/trainer/trainer.py", line 621, in evaluate
    self.eval_collector.eval_batch_collect(
  File "/root/miniconda3/lib/python3.10/site-packages/recbole/evaluator/collector.py", line 161, in eval_batch_collect
    _, topk_idx = torch.topk(
RuntimeError: selected index k out of range

**Comment by Lotus-Blue** [comment]
兄弟，yelp原子文件你是只添加inter，user和item吗？

**Comment by Lotus-Blue** [comment]
我的报错
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'item_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 77, in <module>
    run_single_model(args)
  File "main.py", line 36, in run_single_model
    dataset = create_dataset(config)
  File "/usr/local/lib/python3.6/site-packages/recbole/data/utils.py", line 55, in create_dataset
    return Dataset(config)
  File "/usr/local/lib/python3.6/site-packages/recbole/data/dataset/dataset.py", line 98, in __init__
    self._from_scratch()
  File "/usr/local/lib/python3.6/site-packages/recbole/data/dataset/dataset.py", line 109, in _from_scratch
    self._data_processing()
  File "/usr/local/lib/python3.6/site-packages/recbole/data/dataset/dataset.py", line 151, in _data_processing
    self._data_filtering()
  File "/usr/local/lib/python3.6/site-packages/recbole/data/dataset/dataset.py", line 173, in _data_filtering
    self._filter_nan_user_or_item()
  File "/usr/local/lib/python3.6/site-packages/recbole/data/dataset/dataset.py", line 572, in _filter_nan_user_or_item
    dropped_inter = self.inter_feat.index[self.inter_feat[field].isnull()]
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'item_id'

**Comment by Lotus-Blue** [comment]
我是不是下载错数据集了，我这边打开是business_id，不是item_id？

**Comment by njt123123** [comment]
你的数据集在哪里下载的？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月15日(周三) 下午5:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1)




 
我是不是下载错数据集了，我这边打开是business_id，不是item_id？

**Comment by Lotus-Blue** [comment]
> 你的数据集在哪里下载的？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年11月15日(周三) 下午5:11 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1) 我是不是下载错数据集了，我这边打开是business_id，不是item_id？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

https://recbole.io/cn/dataset_list.html，下面的Yelp2022

**Comment by Lotus-Blue** [comment]
> 你的数据集在哪里下载的？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年11月15日(周三) 下午5:11 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1) 我是不是下载错数据集了，我这边打开是business_id，不是item_id？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

处理完之后inter文件是这样的
![image](https://github.com/WeiHeCnSH/CGCL-Pytorch-master/assets/45590660/9182d6c6-75b7-40c7-8116-ac612cfe9c9c)

**Comment by njt123123** [comment]
你看一下能不能把yelp.inter文件中的business_id改成item_id，或者把yelp.yaml文件中的item_id改成business_id


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WeiHeCnSH/CGCL-Pytorch-master"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月15日(星期三) 下午5:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1)





  
你的数据集在哪里下载的？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年11月15日(周三) 下午5:11 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1) 我是不是下载错数据集了，我这边打开是business_id，不是item_id？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
处理完之后inter文件是这样的

**Comment by Lotus-Blue** [comment]
> item_id

business_id改成item_id,改了之后又出现这个问题
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    run_single_model(args)
  File "main.py", line 39, in run_single_model
    train_data, valid_data, test_data = data_preparation(config, dataset)
  File "/usr/local/lib/python3.6/site-packages/recbole/data/utils.py", line 76, in data_preparation
    es = EvalSetting(config)
  File "/usr/local/lib/python3.6/site-packages/recbole/config/eval_setting.py", line 83, in __init__
    self.es_str = [_.strip() for _ in config['eval_setting'].split(',')]
AttributeError: 'dict' object has no attribute 'split'

**Comment by Lotus-Blue** [comment]
跟玄学一样，头都快炸了

**Comment by Lotus-Blue** [comment]
兄弟你现在跑通了吗

**Comment by njt123123** [comment]
改yelp.yaml文件试试看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WeiHeCnSH/CGCL-Pytorch-master"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月15日(星期三) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1)





 
跟玄学一样，头都快炸了

**Comment by njt123123** [comment]
没


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WeiHeCnSH/CGCL-Pytorch-master"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月15日(星期三) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1)





 
兄弟你现在跑通了吗

**Comment by Lotus-Blue** [comment]
> 改yelp.yaml文件试试看
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "WeiHeCnSH/CGCL-Pytorch-master" ***@***.***&gt;; 发送时间:&nbsp;2023年11月15日(星期三) 下午5:28 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1) 跟玄学一样，头都快炸了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

yelp.yalm也改了试试，不行，我也不清楚为什么

**Comment by njt123123** [comment]
改yelp.yaml文件出现什么错误？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WeiHeCnSH/CGCL-Pytorch-master"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月15日(星期三) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1)





  
改yelp.yaml文件试试看
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "WeiHeCnSH/CGCL-Pytorch-master" @.&gt;; 发送时间:&nbsp;2023年11月15日(星期三) 下午5:28 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1) 跟玄学一样，头都快炸了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
yelp.yalm也改了试试，不行，我也不清楚为什么

**Comment by Lotus-Blue** [comment]
> 没
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "WeiHeCnSH/CGCL-Pytorch-master" ***@***.***&gt;; 发送时间:&nbsp;2023年11月15日(星期三) 下午5:28 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1) 兄弟你现在跑通了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

兄弟你可传传你那三个yelp原子文件给我跑跑看看吗？

> 改yelp.yaml文件出现什么错误？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "WeiHeCnSH/CGCL-Pytorch-master" ***@***.***&gt;; 发送时间:&nbsp;2023年11月15日(星期三) 下午5:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1) 改yelp.yaml文件试试看 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "WeiHeCnSH/CGCL-Pytorch-master" @.&gt;; 发送时间:&nbsp;2023年11月15日(星期三) 下午5:28 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1) 跟玄学一样，头都快炸了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; yelp.yalm也改了试试，不行，我也不清楚为什么 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

还是一样的错误
Remain Fields: ['user_id', 'business_id']
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    run_single_model(args)
  File "main.py", line 39, in run_single_model
    train_data, valid_data, test_data = data_preparation(config, dataset)
  File "/usr/local/lib/python3.6/site-packages/recbole/data/utils.py", line 76, in data_preparation
    es = EvalSetting(config)
  File "/usr/local/lib/python3.6/site-packages/recbole/config/eval_setting.py", line 83, in __init__
    self.es_str = [_.strip() for _ in config['eval_setting'].split(',')]
AttributeError: 'dict' object has no attribute 'split'

**Comment by Lotus-Blue** [comment]
兄弟，要不你把你那边的yelp三个原子文件传给我看看，我这边跑看看是不是你那个问题，用https://cowtransfer.com/login这个传

**Comment by WeiHeCnSH** [comment]
您好！ 您的问题已经被我们注意到，根据您所提供的信息显示是k值超越过了最大数组范围，请调节k值的范围进行实验。此外，如果需要进行进一步的分析，我们希望您可以提供所运行的数据集、运行环境、运行参数等信息。因此，为了快速的能够运行示例，我们建议优先在yelp、gowalla等被recbole处理的数据集上运行。
祝好！
                                                                                                              Send By SXY

**Comment by njt123123** [comment]
你用NCL那篇论文的代码去跑yelp这个数据集，没有yelp那个数据集的话会自动下载的，我那个yelp数据集就是这样下载的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WeiHeCnSH/CGCL-Pytorch-master"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月15日(星期三) 下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1)





 
兄弟，要不你把你那边的yelp三个原子文件传给我看看，我这边跑看看是不是你那个问题，用https://cowtransfer.com/login这个传

**Comment by Lotus-Blue** [comment]
> 你用NCL那篇论文的代码去跑yelp这个数据集，没有yelp那个数据集的话会自动下载的，我那个yelp数据集就是这样下载的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "WeiHeCnSH/CGCL-Pytorch-master" ***@***.***&gt;; 发送时间:&nbsp;2023年11月15日(星期三) 下午5:40 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [WeiHeCnSH/CGCL-Pytorch-master] 为什么会出现这个错误？ (Issue #1) 兄弟，要不你把你那边的yelp三个原子文件传给我看看，我这边跑看看是不是你那个问题，用[https://cowtransfer.com/login这个传](https://cowtransfer.com/login%E8%BF%99%E4%B8%AA%E4%BC%A0) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

好，我看看那篇论文，多谢兄弟了

**Comment by WeiHeCnSH** [comment]
亲爱的读者：
   我们注意到您们目前面临非常多的问题，但是由于网络原因，之前的回答并没有成功的回复，请先按照上面的回答进行尝试修改，如果有其他问题，请再与我们联系。
   祝好！
                                                                          Send By SXY
